//
// Copyright (C) 2022-2023 Intel Corporation.
// SPDX-License-Identifier: Apache 2.0
//

// RUN: vpux-opt --mlir-print-debuginfo --init-compiler="vpu-arch=%arch% allow-custom-values=true" --lower-VPUIP-to-ELF %data_path_npu%/profiling-40XX.mlir.txt | vpux-translate --vpu-arch=%arch% --export-ELF -o %t
// RUN: prof_parser -b %t -p %data_path_npu%/profiling-0-40XX.bin -f json -vv | FileCheck %s
// REQUIRES: arch-NPU40XX

// CHECK: {"traceEvents":[
// CHECK-NEXT: {"name": "process_name", "ph": "M", "pid":0, "args": {"name" : "Cluster (0)"}},
// CHECK-NEXT: {"name": "process_sort_index", "ph": "M", "pid":0, "args": {"sort_index" : "0"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":0, "tid":0, "args": {"name" : "DPU"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":0, "tid":1, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":0, "tid":2, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":0, "tid":3, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":0, "tid":4, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "process_name", "ph": "M", "pid":1, "args": {"name" : "Cluster (1)"}},
// CHECK-NEXT: {"name": "process_sort_index", "ph": "M", "pid":1, "args": {"sort_index" : "1"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":1, "tid":0, "args": {"name" : "DPU"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":1, "tid":1, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":1, "tid":2, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":1, "tid":3, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":1, "tid":4, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "process_name", "ph": "M", "pid":2, "args": {"name" : "Cluster (2)"}},
// CHECK-NEXT: {"name": "process_sort_index", "ph": "M", "pid":2, "args": {"sort_index" : "2"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":2, "tid":0, "args": {"name" : "DPU"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":2, "tid":1, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":2, "tid":2, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":2, "tid":3, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":2, "tid":4, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "process_name", "ph": "M", "pid":3, "args": {"name" : "Cluster (3)"}},
// CHECK-NEXT: {"name": "process_sort_index", "ph": "M", "pid":3, "args": {"sort_index" : "3"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":3, "tid":0, "args": {"name" : "DPU"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":3, "tid":1, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":3, "tid":2, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":3, "tid":3, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":3, "tid":4, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "process_name", "ph": "M", "pid":4, "args": {"name" : "Cluster (4)"}},
// CHECK-NEXT: {"name": "process_sort_index", "ph": "M", "pid":4, "args": {"sort_index" : "4"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":4, "tid":0, "args": {"name" : "DPU"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":4, "tid":1, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":4, "tid":2, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":4, "tid":3, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":4, "tid":4, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "process_name", "ph": "M", "pid":5, "args": {"name" : "Cluster (5)"}},
// CHECK-NEXT: {"name": "process_sort_index", "ph": "M", "pid":5, "args": {"sort_index" : "5"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":5, "tid":0, "args": {"name" : "DPU"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":5, "tid":1, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":5, "tid":2, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":5, "tid":3, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "process_name", "ph": "M", "pid":6, "args": {"name" : "Layers"}},
// CHECK-NEXT: {"name": "process_sort_index", "ph": "M", "pid":6, "args": {"sort_index" : "6"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":6, "tid":0, "args": {"name" : "Layers"}},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_0", "cat":"DPU", "ph":"X", "ts":0.000, "dur":0.206, "pid":0, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_0/variant_0", "cat":"DPU", "ph":"X", "ts":0.000, "dur":0.206, "pid":0, "tid":1},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_0", "cat":"DPU", "ph":"X", "ts":7.689, "dur":1.893, "pid":0, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_0/variant_0", "cat":"DPU", "ph":"X", "ts":7.689, "dur":1.893, "pid":0, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_0", "cat":"DPU", "ph":"X", "ts":9.637, "dur":1.611, "pid":0, "tid":0},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_0/variant_0", "cat":"DPU", "ph":"X", "ts":9.637, "dur":1.091, "pid":0, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_0/variant_1", "cat":"DPU", "ph":"X", "ts":10.717, "dur":0.531, "pid":0, "tid":2},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_0", "cat":"DPU", "ph":"X", "ts":11.303, "dur":3.643, "pid":0, "tid":0},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_0/variant_0", "cat":"DPU", "ph":"X", "ts":11.303, "dur":3.643, "pid":0, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_0", "cat":"DPU", "ph":"X", "ts":14.997, "dur":0.939, "pid":0, "tid":0},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_0/variant_0", "cat":"DPU", "ph":"X", "ts":14.997, "dur":0.939, "pid":0, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_0/cluster_0", "cat":"SW", "ph":"X", "ts":43.749, "dur":11.927, "pid":0, "tid":3, "args":{"Total cycles:": "12119", "Stall cycles:": "11448", "LSU0 stall cycles:": "737", "LSU1 stall cycles:": "58", "Instruction stall cycles:": "10653"}},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_1/cluster_0", "cat":"SW", "ph":"X", "ts":43.905, "dur":11.770, "pid":0, "tid":4, "args":{"Total cycles:": "12112", "Stall cycles:": "11448", "LSU0 stall cycles:": "891", "LSU1 stall cycles:": "58", "Instruction stall cycles:": "10499"}},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_1", "cat":"DPU", "ph":"X", "ts":1.095, "dur":0.206, "pid":1, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_1/variant_0", "cat":"DPU", "ph":"X", "ts":1.095, "dur":0.206, "pid":1, "tid":1},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_1", "cat":"DPU", "ph":"X", "ts":7.689, "dur":1.893, "pid":1, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_1/variant_0", "cat":"DPU", "ph":"X", "ts":7.689, "dur":1.893, "pid":1, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_1", "cat":"DPU", "ph":"X", "ts":9.637, "dur":1.663, "pid":1, "tid":0},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_1/variant_0", "cat":"DPU", "ph":"X", "ts":9.637, "dur":1.091, "pid":1, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_1/variant_1", "cat":"DPU", "ph":"X", "ts":10.713, "dur":0.587, "pid":1, "tid":2},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_1", "cat":"DPU", "ph":"X", "ts":11.303, "dur":3.643, "pid":1, "tid":0},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_1/variant_0", "cat":"DPU", "ph":"X", "ts":11.303, "dur":3.643, "pid":1, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_1", "cat":"DPU", "ph":"X", "ts":15.007, "dur":0.928, "pid":1, "tid":0},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_1/variant_0", "cat":"DPU", "ph":"X", "ts":15.007, "dur":0.928, "pid":1, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_0/cluster_1", "cat":"SW", "ph":"X", "ts":43.905, "dur":11.562, "pid":1, "tid":3, "args":{"Total cycles:": "12105", "Stall cycles:": "11274", "LSU0 stall cycles:": "696", "LSU1 stall cycles:": "55", "Instruction stall cycles:": "10523"}},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_1/cluster_1", "cat":"SW", "ph":"X", "ts":44.686, "dur":10.937, "pid":1, "tid":4, "args":{"Total cycles:": "11106", "Stall cycles:": "10617", "LSU0 stall cycles:": "845", "LSU1 stall cycles:": "55", "Instruction stall cycles:": "9717"}},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_2", "cat":"DPU", "ph":"X", "ts":1.930, "dur":0.204, "pid":2, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_2/variant_0", "cat":"DPU", "ph":"X", "ts":1.930, "dur":0.204, "pid":2, "tid":1},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_2", "cat":"DPU", "ph":"X", "ts":7.688, "dur":1.894, "pid":2, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_2/variant_0", "cat":"DPU", "ph":"X", "ts":7.688, "dur":1.894, "pid":2, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_2", "cat":"DPU", "ph":"X", "ts":9.634, "dur":1.666, "pid":2, "tid":0},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_2/variant_0", "cat":"DPU", "ph":"X", "ts":9.634, "dur":1.093, "pid":2, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_2/variant_1", "cat":"DPU", "ph":"X", "ts":10.707, "dur":0.593, "pid":2, "tid":2},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_2", "cat":"DPU", "ph":"X", "ts":11.304, "dur":3.642, "pid":2, "tid":0},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_2/variant_0", "cat":"DPU", "ph":"X", "ts":11.304, "dur":3.642, "pid":2, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_2", "cat":"DPU", "ph":"X", "ts":14.959, "dur":0.977, "pid":2, "tid":0},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_2/variant_0", "cat":"DPU", "ph":"X", "ts":14.959, "dur":0.977, "pid":2, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_0/cluster_2", "cat":"SW", "ph":"X", "ts":45.207, "dur":10.468, "pid":2, "tid":3, "args":{"Total cycles:": "10588", "Stall cycles:": "9912", "LSU0 stall cycles:": "866", "LSU1 stall cycles:": "57", "Instruction stall cycles:": "8989"}},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_1/cluster_2", "cat":"SW", "ph":"X", "ts":45.468, "dur":10.000, "pid":2, "tid":4, "args":{"Total cycles:": "10440", "Stall cycles:": "9638", "LSU0 stall cycles:": "698", "LSU1 stall cycles:": "55", "Instruction stall cycles:": "8885"}},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_3", "cat":"DPU", "ph":"X", "ts":2.763, "dur":0.204, "pid":3, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_3/variant_0", "cat":"DPU", "ph":"X", "ts":2.763, "dur":0.204, "pid":3, "tid":1},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_3", "cat":"DPU", "ph":"X", "ts":7.687, "dur":1.895, "pid":3, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_3/variant_0", "cat":"DPU", "ph":"X", "ts":7.687, "dur":1.895, "pid":3, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_3", "cat":"DPU", "ph":"X", "ts":9.647, "dur":1.601, "pid":3, "tid":0},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_3/variant_0", "cat":"DPU", "ph":"X", "ts":9.647, "dur":1.080, "pid":3, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_3/variant_1", "cat":"DPU", "ph":"X", "ts":10.708, "dur":0.540, "pid":3, "tid":2},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_3", "cat":"DPU", "ph":"X", "ts":11.301, "dur":3.646, "pid":3, "tid":0},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_3/variant_0", "cat":"DPU", "ph":"X", "ts":11.301, "dur":3.646, "pid":3, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_3", "cat":"DPU", "ph":"X", "ts":15.006, "dur":0.930, "pid":3, "tid":0},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_3/variant_0", "cat":"DPU", "ph":"X", "ts":15.006, "dur":0.930, "pid":3, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_0/cluster_3", "cat":"SW", "ph":"X", "ts":46.614, "dur":9.010, "pid":3, "tid":3, "args":{"Total cycles:": "9065", "Stall cycles:": "8584", "LSU0 stall cycles:": "677", "LSU1 stall cycles:": "53", "Instruction stall cycles:": "7854"}},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_1/cluster_3", "cat":"SW", "ph":"X", "ts":47.603, "dur":8.072, "pid":3, "tid":4, "args":{"Total cycles:": "8069", "Stall cycles:": "7589", "LSU0 stall cycles:": "677", "LSU1 stall cycles:": "54", "Instruction stall cycles:": "6858"}},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_4", "cat":"DPU", "ph":"X", "ts":3.596, "dur":0.204, "pid":4, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_4/variant_0", "cat":"DPU", "ph":"X", "ts":3.596, "dur":0.204, "pid":4, "tid":1},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_4", "cat":"DPU", "ph":"X", "ts":7.688, "dur":1.894, "pid":4, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_4/variant_0", "cat":"DPU", "ph":"X", "ts":7.688, "dur":1.894, "pid":4, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_4", "cat":"DPU", "ph":"X", "ts":9.644, "dur":1.656, "pid":4, "tid":0},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_4/variant_0", "cat":"DPU", "ph":"X", "ts":9.644, "dur":1.084, "pid":4, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_4/variant_1", "cat":"DPU", "ph":"X", "ts":10.707, "dur":0.594, "pid":4, "tid":2},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_4", "cat":"DPU", "ph":"X", "ts":11.335, "dur":1.841, "pid":4, "tid":0},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_4/variant_0", "cat":"DPU", "ph":"X", "ts":11.335, "dur":1.841, "pid":4, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_4", "cat":"DPU", "ph":"X", "ts":14.965, "dur":0.971, "pid":4, "tid":0},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_4/variant_0", "cat":"DPU", "ph":"X", "ts":14.965, "dur":0.971, "pid":4, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_0/cluster_4", "cat":"SW", "ph":"X", "ts":49.478, "dur":5.729, "pid":4, "tid":3, "args":{"Total cycles:": "5802", "Stall cycles:": "5348", "LSU0 stall cycles:": "673", "LSU1 stall cycles:": "62", "Instruction stall cycles:": "4613"}},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_1/cluster_4", "cat":"SW", "ph":"X", "ts":51.145, "dur":4.114, "pid":4, "tid":4, "args":{"Total cycles:": "4051", "Stall cycles:": "3581", "LSU0 stall cycles:": "666", "LSU1 stall cycles:": "55", "Instruction stall cycles:": "2860"}},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_5", "cat":"DPU", "ph":"X", "ts":4.430, "dur":0.152, "pid":5, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_5/variant_0", "cat":"DPU", "ph":"X", "ts":4.430, "dur":0.152, "pid":5, "tid":1},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_5", "cat":"DPU", "ph":"X", "ts":7.688, "dur":1.894, "pid":5, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_5/variant_0", "cat":"DPU", "ph":"X", "ts":7.688, "dur":1.894, "pid":5, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_5", "cat":"DPU", "ph":"X", "ts":9.616, "dur":1.528, "pid":5, "tid":0},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_5/variant_0", "cat":"DPU", "ph":"X", "ts":9.616, "dur":1.007, "pid":5, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_5/variant_1", "cat":"DPU", "ph":"X", "ts":10.642, "dur":0.502, "pid":5, "tid":1},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_5", "cat":"DPU", "ph":"X", "ts":11.335, "dur":1.841, "pid":5, "tid":0},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_5/variant_0", "cat":"DPU", "ph":"X", "ts":11.335, "dur":1.841, "pid":5, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_5", "cat":"DPU", "ph":"X", "ts":14.961, "dur":0.975, "pid":5, "tid":0},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_5/variant_0", "cat":"DPU", "ph":"X", "ts":14.961, "dur":0.975, "pid":5, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_0/cluster_5", "cat":"SW", "ph":"X", "ts":53.176, "dur":3.645, "pid":5, "tid":2, "args":{"Total cycles:": "3836", "Stall cycles:": "3186", "LSU0 stall cycles:": "648", "LSU1 stall cycles:": "58", "Instruction stall cycles:": "2480"}},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_1/cluster_5", "cat":"SW", "ph":"X", "ts":54.530, "dur":3.645, "pid":5, "tid":3, "args":{"Total cycles:": "3593", "Stall cycles:": "2954", "LSU0 stall cycles:": "1155", "LSU1 stall cycles:": "59", "Instruction stall cycles:": "1740"}},
// CHECK-NEXT: {"name":"conv1/WithoutBiases", "cat":"Layer", "ph":"X", "ts":0.000, "dur":9.582, "pid":6, "tid":0, "args":{"Layer type": "Convolution", "DPU time:": "12us 539ns"}},
// CHECK-NEXT: {"name":"relu1", "cat":"Layer", "ph":"X", "ts":9.616, "dur":1.684, "pid":6, "tid":0, "args":{"Layer type": "Relu", "DPU time:": "9us 725ns"}},
// CHECK-NEXT: {"name":"conv2/WithoutBiases", "cat":"Layer", "ph":"X", "ts":11.301, "dur":3.646, "pid":6, "tid":0, "args":{"Layer type": "Convolution", "DPU time:": "18us 256ns"}},
// CHECK-NEXT: {"name":"relu2", "cat":"Layer", "ph":"X", "ts":14.959, "dur":43.216, "pid":6, "tid":0, "args":{"Layer type": "Relu", "DPU time:": "5us 720ns", "Shave time:": "100us 879ns"}}
// CHECK-NEXT: ],
// CHECK-NEXT: "taskStatistics": {
// CHECK-NEXT: "total duration":58.175,
// CHECK-NEXT: "DMA duration":0.000,
// CHECK-NEXT: "DPU duration":9.378,
// CHECK-NEXT: "SW duration":14.426,
// CHECK-NEXT: "M2I duration":0.000,
// CHECK-NEXT: "DMA-DPU overlap":0.000,
// CHECK-NEXT: "DMA-SW overlap":0.000,
// CHECK-NEXT: "SW-DPU overlap":0.000,
// CHECK-NEXT: "all tasks union":23.804,
// CHECK-NEXT: "total idle":34.371,
// CHECK-NEXT: "SW duration without DPU overlap":14.426,
// CHECK-NEXT: "DMA duration without overlaps":0.000,
// CHECK-NEXT: "Sum of DMA task durations":0.000,
// CHECK-NEXT: "Sum of DPU task durations":46.240,
// CHECK-NEXT: "Sum of SW task durations":100.879,
// CHECK-NEXT: "Sum of M2I task durations":0.000
// CHECK-NEXT: },
// CHECK-NEXT: "workpoint": { "freq": 1850.0, "status": "OK" },
// CHECK-NEXT: "displayTimeUnit": "ns"
// CHECK-NEXT: }
