//
// Copyright (C) 2024 Intel Corporation.
// SPDX-License-Identifier: Apache 2.0
//

// RUN: vpux-opt --mlir-print-debuginfo --init-compiler="vpu-arch=%arch% allow-custom-values=true" --lower-VPUIP-to-ELF %data_path_npu%/profiling-40XX.mlir.txt | vpux-translate --vpu-arch=%arch% --export-ELF -o %t
// RUN: prof_parser -b %t -p %data_path_npu%/profiling-0-40XX.bin -f json -vv | FileCheck %s
// REQUIRES: arch-VPUX40XX

// CHECK: {"traceEvents":[
// CHECK-NEXT: {"name": "process_name", "ph": "M", "pid":0, "args": {"name" : "Cluster (0)"}},
// CHECK-NEXT: {"name": "process_sort_index", "ph": "M", "pid":0, "args": {"sort_index" : "0"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":0, "tid":0, "args": {"name" : "DPU"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":0, "tid":1, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":0, "tid":2, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":0, "tid":3, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":0, "tid":4, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "process_name", "ph": "M", "pid":1, "args": {"name" : "Cluster (1)"}},
// CHECK-NEXT: {"name": "process_sort_index", "ph": "M", "pid":1, "args": {"sort_index" : "1"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":1, "tid":0, "args": {"name" : "DPU"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":1, "tid":1, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":1, "tid":2, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":1, "tid":3, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":1, "tid":4, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "process_name", "ph": "M", "pid":2, "args": {"name" : "Cluster (2)"}},
// CHECK-NEXT: {"name": "process_sort_index", "ph": "M", "pid":2, "args": {"sort_index" : "2"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":2, "tid":0, "args": {"name" : "DPU"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":2, "tid":1, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":2, "tid":2, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":2, "tid":3, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":2, "tid":4, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "process_name", "ph": "M", "pid":3, "args": {"name" : "Cluster (3)"}},
// CHECK-NEXT: {"name": "process_sort_index", "ph": "M", "pid":3, "args": {"sort_index" : "3"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":3, "tid":0, "args": {"name" : "DPU"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":3, "tid":1, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":3, "tid":2, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":3, "tid":3, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":3, "tid":4, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "process_name", "ph": "M", "pid":4, "args": {"name" : "Cluster (4)"}},
// CHECK-NEXT: {"name": "process_sort_index", "ph": "M", "pid":4, "args": {"sort_index" : "4"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":4, "tid":0, "args": {"name" : "DPU"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":4, "tid":1, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":4, "tid":2, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":4, "tid":3, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":4, "tid":4, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "process_name", "ph": "M", "pid":5, "args": {"name" : "Cluster (5)"}},
// CHECK-NEXT: {"name": "process_sort_index", "ph": "M", "pid":5, "args": {"sort_index" : "5"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":5, "tid":0, "args": {"name" : "DPU"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":5, "tid":1, "args": {"name" : "DPU / Variants"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":5, "tid":2, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":5, "tid":3, "args": {"name" : "SW / Shave"}},
// CHECK-NEXT: {"name": "process_name", "ph": "M", "pid":6, "args": {"name" : "Layers"}},
// CHECK-NEXT: {"name": "process_sort_index", "ph": "M", "pid":6, "args": {"sort_index" : "6"}},
// CHECK-NEXT: {"name": "thread_name", "ph": "M", "pid":6, "tid":0, "args": {"name" : "Layers"}},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_0", "cat":"DPU", "ph":"X", "ts":3.229, "dur":0.205, "pid":0, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_0/variant_0", "cat":"DPU", "ph":"X", "ts":3.229, "dur":0.205, "pid":0, "tid":1},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_0", "cat":"DPU", "ph":"X", "ts":7.320, "dur":1.894, "pid":0, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_0/variant_0", "cat":"DPU", "ph":"X", "ts":7.320, "dur":1.894, "pid":0, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_0", "cat":"DPU", "ph":"X", "ts":9.268, "dur":1.665, "pid":0, "tid":0},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_0/variant_0", "cat":"DPU", "ph":"X", "ts":9.268, "dur":1.092, "pid":0, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_0/variant_1", "cat":"DPU", "ph":"X", "ts":10.345, "dur":0.588, "pid":0, "tid":2},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_0", "cat":"DPU", "ph":"X", "ts":10.936, "dur":3.643, "pid":0, "tid":0},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_0/variant_0", "cat":"DPU", "ph":"X", "ts":10.936, "dur":3.643, "pid":0, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_0", "cat":"DPU", "ph":"X", "ts":14.630, "dur":0.939, "pid":0, "tid":0},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_0/variant_0", "cat":"DPU", "ph":"X", "ts":14.630, "dur":0.939, "pid":0, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_1/cluster_0", "cat":"SW", "ph":"X", "ts":36.976, "dur":9.583, "pid":0, "tid":3},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_0/cluster_0", "cat":"SW", "ph":"X", "ts":37.184, "dur":9.947, "pid":0, "tid":4},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_1", "cat":"DPU", "ph":"X", "ts":0.000, "dur":0.204, "pid":1, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_1/variant_0", "cat":"DPU", "ph":"X", "ts":0.000, "dur":0.204, "pid":1, "tid":1},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_1", "cat":"DPU", "ph":"X", "ts":7.321, "dur":1.894, "pid":1, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_1/variant_0", "cat":"DPU", "ph":"X", "ts":7.321, "dur":1.894, "pid":1, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_1", "cat":"DPU", "ph":"X", "ts":9.278, "dur":1.656, "pid":1, "tid":0},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_1/variant_0", "cat":"DPU", "ph":"X", "ts":9.278, "dur":1.083, "pid":1, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_1/variant_1", "cat":"DPU", "ph":"X", "ts":10.343, "dur":0.590, "pid":1, "tid":2},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_1", "cat":"DPU", "ph":"X", "ts":10.936, "dur":3.643, "pid":1, "tid":0},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_1/variant_0", "cat":"DPU", "ph":"X", "ts":10.936, "dur":3.643, "pid":1, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_1", "cat":"DPU", "ph":"X", "ts":14.588, "dur":0.981, "pid":1, "tid":0},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_1/variant_0", "cat":"DPU", "ph":"X", "ts":14.588, "dur":0.981, "pid":1, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_0/cluster_1", "cat":"SW", "ph":"X", "ts":37.184, "dur":9.375, "pid":1, "tid":3},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_1/cluster_1", "cat":"SW", "ph":"X", "ts":37.184, "dur":9.375, "pid":1, "tid":4},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_2", "cat":"DPU", "ph":"X", "ts":0.001, "dur":0.152, "pid":2, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_2/variant_0", "cat":"DPU", "ph":"X", "ts":0.001, "dur":0.152, "pid":2, "tid":1},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_2", "cat":"DPU", "ph":"X", "ts":7.321, "dur":1.894, "pid":2, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_2/variant_0", "cat":"DPU", "ph":"X", "ts":7.321, "dur":1.894, "pid":2, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_2", "cat":"DPU", "ph":"X", "ts":9.273, "dur":1.660, "pid":2, "tid":0},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_2/variant_0", "cat":"DPU", "ph":"X", "ts":9.273, "dur":1.087, "pid":2, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_2/variant_1", "cat":"DPU", "ph":"X", "ts":10.344, "dur":0.589, "pid":2, "tid":2},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_2", "cat":"DPU", "ph":"X", "ts":10.935, "dur":3.644, "pid":2, "tid":0},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_2/variant_0", "cat":"DPU", "ph":"X", "ts":10.935, "dur":3.644, "pid":2, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_2", "cat":"DPU", "ph":"X", "ts":14.589, "dur":0.979, "pid":2, "tid":0},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_2/variant_0", "cat":"DPU", "ph":"X", "ts":14.589, "dur":0.979, "pid":2, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_1/cluster_2", "cat":"SW", "ph":"X", "ts":36.715, "dur":9.843, "pid":2, "tid":3},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_0/cluster_2", "cat":"SW", "ph":"X", "ts":36.976, "dur":10.156, "pid":2, "tid":4},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_3", "cat":"DPU", "ph":"X", "ts":0.001, "dur":0.152, "pid":3, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_3/variant_0", "cat":"DPU", "ph":"X", "ts":0.001, "dur":0.152, "pid":3, "tid":1},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_3", "cat":"DPU", "ph":"X", "ts":7.321, "dur":1.894, "pid":3, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_3/variant_0", "cat":"DPU", "ph":"X", "ts":7.321, "dur":1.894, "pid":3, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_3", "cat":"DPU", "ph":"X", "ts":9.286, "dur":1.596, "pid":3, "tid":0},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_3/variant_0", "cat":"DPU", "ph":"X", "ts":9.286, "dur":1.075, "pid":3, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_3/variant_1", "cat":"DPU", "ph":"X", "ts":10.349, "dur":0.532, "pid":3, "tid":2},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_3", "cat":"DPU", "ph":"X", "ts":10.935, "dur":3.644, "pid":3, "tid":0},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_3/variant_0", "cat":"DPU", "ph":"X", "ts":10.935, "dur":3.644, "pid":3, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_3", "cat":"DPU", "ph":"X", "ts":14.592, "dur":0.977, "pid":3, "tid":0},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_3/variant_0", "cat":"DPU", "ph":"X", "ts":14.592, "dur":0.977, "pid":3, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_1/cluster_3", "cat":"SW", "ph":"X", "ts":36.715, "dur":9.895, "pid":3, "tid":3},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_0/cluster_3", "cat":"SW", "ph":"X", "ts":37.184, "dur":9.427, "pid":3, "tid":4},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_4", "cat":"DPU", "ph":"X", "ts":0.001, "dur":0.152, "pid":4, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_4/variant_0", "cat":"DPU", "ph":"X", "ts":0.001, "dur":0.152, "pid":4, "tid":1},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_4", "cat":"DPU", "ph":"X", "ts":7.321, "dur":1.893, "pid":4, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_4/variant_0", "cat":"DPU", "ph":"X", "ts":7.321, "dur":1.893, "pid":4, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_4", "cat":"DPU", "ph":"X", "ts":9.279, "dur":1.655, "pid":4, "tid":0},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_4/variant_0", "cat":"DPU", "ph":"X", "ts":9.279, "dur":1.082, "pid":4, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_4/variant_1", "cat":"DPU", "ph":"X", "ts":10.345, "dur":0.588, "pid":4, "tid":2},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_4", "cat":"DPU", "ph":"X", "ts":10.972, "dur":1.837, "pid":4, "tid":0},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_4/variant_0", "cat":"DPU", "ph":"X", "ts":10.972, "dur":1.837, "pid":4, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_4", "cat":"DPU", "ph":"X", "ts":14.588, "dur":0.981, "pid":4, "tid":0},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_4/variant_0", "cat":"DPU", "ph":"X", "ts":14.588, "dur":0.981, "pid":4, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_1/cluster_4", "cat":"SW", "ph":"X", "ts":36.715, "dur":9.843, "pid":4, "tid":3},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_0/cluster_4", "cat":"SW", "ph":"X", "ts":36.976, "dur":9.583, "pid":4, "tid":4},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_5", "cat":"DPU", "ph":"X", "ts":0.001, "dur":0.152, "pid":5, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/cluster_5/variant_0", "cat":"DPU", "ph":"X", "ts":0.001, "dur":0.152, "pid":5, "tid":1},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_5", "cat":"DPU", "ph":"X", "ts":7.322, "dur":1.893, "pid":5, "tid":0},
// CHECK-NEXT: {"name":"conv1/WithoutBiases?t_Convolution/Duplicated_2/cluster_5/variant_0", "cat":"DPU", "ph":"X", "ts":7.322, "dur":1.893, "pid":5, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_5", "cat":"DPU", "ph":"X", "ts":9.253, "dur":1.524, "pid":5, "tid":0},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_5/variant_0", "cat":"DPU", "ph":"X", "ts":9.253, "dur":1.004, "pid":5, "tid":1},
// CHECK-NEXT: {"name":"relu1?t_Relu/cluster_5/variant_1", "cat":"DPU", "ph":"X", "ts":10.272, "dur":0.505, "pid":5, "tid":1},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_5", "cat":"DPU", "ph":"X", "ts":10.969, "dur":1.839, "pid":5, "tid":0},
// CHECK-NEXT: {"name":"conv2/WithoutBiases?t_Convolution/cluster_5/variant_0", "cat":"DPU", "ph":"X", "ts":10.969, "dur":1.839, "pid":5, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_5", "cat":"DPU", "ph":"X", "ts":14.592, "dur":0.977, "pid":5, "tid":0},
// CHECK-NEXT: {"name":"relu2?t_Relu/cluster_5/variant_0", "cat":"DPU", "ph":"X", "ts":14.592, "dur":0.977, "pid":5, "tid":1},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_0/cluster_5", "cat":"SW", "ph":"X", "ts":36.715, "dur":9.843, "pid":5, "tid":2},
// CHECK-NEXT: {"name":"relu2?t_Relu/converted_to_f32/tile_1/cluster_5", "cat":"SW", "ph":"X", "ts":37.184, "dur":9.375, "pid":5, "tid":3},
// CHECK-NEXT: {"name":"conv1/WithoutBiases", "cat":"Layer", "ph":"X", "ts":0.000, "dur":9.215, "pid":6, "tid":0, "args":{"Layer type": "Convolution"}},
// CHECK-NEXT: {"name":"relu1", "cat":"Layer", "ph":"X", "ts":9.253, "dur":1.681, "pid":6, "tid":0, "args":{"Layer type": "Relu"}},
// CHECK-NEXT: {"name":"conv2/WithoutBiases", "cat":"Layer", "ph":"X", "ts":10.935, "dur":3.644, "pid":6, "tid":0, "args":{"Layer type": "Convolution"}},
// CHECK-NEXT: {"name":"relu2", "cat":"Layer", "ph":"X", "ts":14.588, "dur":32.544, "pid":6, "tid":0, "args":{"Layer type": "Relu"}}
// CHECK-NEXT: ],
// CHECK-NEXT: "taskStatistics": {
// CHECK-NEXT: "total duration":47.132,
// CHECK-NEXT: "DMA duration":0.000,
// CHECK-NEXT: "DPU duration":8.610,
// CHECK-NEXT: "SW duration":10.417,
// CHECK-NEXT: "M2I duration":0.000,
// CHECK-NEXT: "DMA-DPU overlap":0.000,
// CHECK-NEXT: "DMA-SW overlap":0.000,
// CHECK-NEXT: "SW-DPU overlap":0.000,
// CHECK-NEXT: "all tasks union":19.027,
// CHECK-NEXT: "total idle":28.105,
// CHECK-NEXT: "SW duration without DPU overlap":10.417,
// CHECK-NEXT: "DMA duration without overlaps":0.000,
// CHECK-NEXT: "Sum of DMA task durations":0.000,
// CHECK-NEXT: "Sum of DPU task durations":46.219,
// CHECK-NEXT: "Sum of SW task durations":116.245,
// CHECK-NEXT: "Sum of M2I task durations":0.000
// CHECK-NEXT: },
// CHECK-NEXT: "displayTimeUnit": "ns"
// CHECK-NEXT: }
 